version: "3.9"
# DB
services:
  xyzwitter_db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: xyzwitter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres